//set values for rock, paper, and scissors
var rock = 0;
var paper = 1;
var scissors = 2;
//variables & buttons
var rock = document.getElementById("rock");
var paper = document.getElementById("paper");
var scissors = document.getElementById("scissors");
//defines j and i
var j = 0
var i = 0
//console logs the value of the button that the player presses
rock.onclick = function functionrock() {
    //assigns a random value to the variable "random"
    var random = Math.floor(Math.random()*3)
    console.log("you chose rock, and"); var j = 0;
    if (random === 0) {
        console.log("the computer chose rock"); 
        var i = 0;
    } else if (random === 1) {
        console.log("the computer chose paper"); 
        var i = 1;
    } else if (random === 2) {
        console.log("the computer chose scissors"); 
        var i = 2;
    }
    //compares variables i and j
    if (i === j) {
        console.log("The game was a tie"); var z = 1;   
    } else if (i === 1) {
        console.log("You lost :(")
    } else if (i === 2) {
        console.log("You win!")
    }
    console.log("----------")
}
paper.onclick = function functionpaper() {
    //assigns a random value to the variable "random"
    var random = Math.floor(Math.random()*3)
    console.log("you chose paper, and"); var j = 1;
    //console logs the random value generated by the computer
    if (random === 0) {
        console.log("the computer chose rock"); 
        var i = 0;
    } else if (random === 1) {
        console.log("the computer chose paper"); 
        var i = 1;
    } else if (random === 2) {
        console.log("the computer chose scissors"); 
        var i = 2;
    }
//compares variables i and j
if (i === j) {
        console.log("The game was a tie"); var z = 1;   
} else if (i === 0) {
    console.log("You win!")
} else if (i === 2) {
    console.log("You lost :(")
}
console.log("----------")
}
scissors.onclick = function functionscissors() {
    //assigns a random value to the variable "random"
    var random = Math.floor(Math.random()*3)
    console.log("you chose scissors, and"); var j = 2;
    //console logs the random value generated by the computer
    if (random === 0) {
        console.log("the computer chose rock"); 
        var i = 0;
    } else if (random === 1) {
        console.log("the computer chose paper"); 
        var i = 1;
    } else if (random === 2) {
        console.log("the computer chose scissors"); 
        var i = 2;
    }
//compares variables i and j
if (i === j) {
        console.log("The game was a tie"); var z = 1;   
    } else if (i === 0) {
        console.log("You lost :(")
    } else if (i === 1) {
        console.log("You win!")
    }
    console.log("----------")
}
//applies it to the html
